### ISSUE TITLE
The query generated while applying a basic filter in Power BI Desktop with direct query mode returns an error

### ISSUE THREAD

**Issue by rupal-bq** [opendistro-for-elasticsearch/sql#662] opened 2020-08-05 20:53 UTC
While applying a basic filter in PBID with direct query mode, the following query is generated 
```
select `OriginCountry`
from 
(
    select `OriginCountry`
    from `kibana_sample_data_flights`
    where `OriginCountry` in ('AE', 'CA')
) as `ITBL`
group by `OriginCountry`
order by `OriginCountry`
limit 501
```
which returns an error as 
```
{
  "error": {
    "reason": "There was internal problem at backend",
    "details": "class com.alibaba.druid.sql.ast.statement.SQLSubqueryTableSource cannot be cast to class com.alibaba.druid.sql.ast.statement.SQLJoinTableSource (com.alibaba.druid.sql.ast.statement.SQLSubqueryTableSource and com.alibaba.druid.sql.ast.statement.SQLJoinTableSource are in unnamed module of loader java.net.FactoryURLClassLoader @d5556bf)",
    "type": "ClassCastException"
  },
  "status": 503
}
```
![image](https://user-images.githubusercontent.com/56703525/89571300-4514f600-d7dc-11ea-9da8-0bad05511e41.png)

**Comment by dai-chen** [comment] 2020-08-06 00:31
Thanks for reporting the issue! I think this is because the query with subquery in FROM and aggregation outside is not supported.

**Comment by vthatiparthy** [comment] 2020-08-19 05:37
I have join field relations and below query is not working 
select m.* from test20 m  join  (select gm.* from test20 where my_join_field='groups' and  gm.groupfk = 1 and gm.deleted = false) as gmm on m.memberpk = gmm.memberfk

Its giving an error as

{
  "error": {
    "reason": "There was internal problem at backend",
    "details": "class com.alibaba.druid.sql.ast.statement.SQLSubqueryTableSource cannot be cast to class com.alibaba.druid.sql.ast.statement.SQLJoinTableSource (com.alibaba.druid.sql.ast.statement.SQLSubqueryTableSource and com.alibaba.druid.sql.ast.statement.SQLJoinTableSource are in unnamed module of loader java.net.FactoryURLClassLoader @7d70638)",
    "type": "ClassCastException"
  },
  "status": 503
}

**Comment by dai-chen** [comment] 2020-11-18 00:30
The issue has been fixed in new query engine (which is experimental and disabled by default). You can enable it to preview by changing the plugin setting: https://github.com/opendistro-for-elasticsearch/sql/blob/master/docs/user/admin/settings.rst#opendistro-sql-engine-new-enabled. Thanks!

@vthatiparthy JOIN support will be added to this improved SQL engine later. Thanks!

**Comment by ankurgupta4891** [comment] 2021-11-06 17:35
I'm running into the same issue with new engine enabled. The simple subquery runs fine but adding `group by` fails with the same error as vthatiparthy reported. For example, [1] passes but [2] fails.

1.
```
select `dest_state_abr`
from 
(
    select `dest_state_abr`
    from `all_flights`
    where `dest_state_abr` in ('GA', 'MA')
) as `ITBL`
```
2. 
```
select `dest_state_abr`
from 
(
    select `dest_state_abr`
    from `all_flights`
    where `dest_state_abr` in ('GA', 'MA')
) as `ITBL`
group by `dest_state_abr`
```

**Comment by joshuali925** [comment] 2021-11-30 21:36
Will track this issue in OpenSearch repo: https://github.com/opensearch-project/sql/issues/308

**Comment by penghuo** [comment] 2022-01-06 22:19
@ankurgupta4891 have u try latest OpenSearch 1.2.3. It has been fixed. https://opensearch.org/downloads.html

```
POST /_plugins/_sql
{
  "query": "SELECT `DestCityName` FROM (SELECT DestCityName FROM opensearch_dashboards_sample_data_flights WHERE DestCityName IS NOT NULL LIMIT 10) as T GROUP BY `DestCityName`"
}

{
  "schema": [
    {
      "name": "DestCityName",
      "type": "keyword"
    }
  ],
  "datarows": [
    [
      "Treviso"
    ],
    [
      "Hyderabad"
    ],
    [
      "Zurich"
    ],
    [
      "Ottawa"
    ],
    [
      "Venice"
    ],
    [
      "Genova"
    ],
    [
      "Sydney"
    ],
    [
      """Xi'an"""
    ]
  ],
  "total": 8,
  "size": 8,
  "status": 200
}
```

**Closed by penghuo** 2022-01-06 22:19 UTC
Labels: bug, BI integration, SQL

**Comment by penghuo** [comment] 2022-01-06 22:28
Currently, OpenSerach doesn't support IN operator. Which is the root cause why your query failed. Please using opensearch-project/sql#308 for tracking.
