### ISSUE TITLE
Problems for selecting on index patterns in JDBC

### ISSUE THREAD

**Issue by HernanMora** [opendistro-for-elasticsearch/sql#9] opened 2019-03-20 14:41 UTC
When I try the plugin on REST it works correctly

```
curl -H "Content-Type: application/json" -XPOST http://localhost:9200/_opendistro/_sql -d '{"query":"select * from my-index* limit 1","parameters":[]}'
```
But when I perform the same test through the JDBC connector I get the following error:

```
curl -H "Content-Type: application/json" -XPOST http://localhost:9200/_opendistro/_sql?format=jdbc -d '{"query":"select * from my-index* limit 1","parameters":[]}'
{
  "error": {
    "reason": "Index type null does not exist",
    "details": "java.lang.IllegalArgumentException: Index type null does not exist\n\tat com.amazon.opendistroforelasticsearch.sql.executor.format.SelectResultSet.loadFromEsState(SelectResultSet.java:109)\n\tat com.amazon.opendistroforelasticsearch.sql.executor.format.SelectResultSet.<init>(SelectResultSet.java:71)\n\tat com.amazon.opendistroforelasticsearch.sql.executor.format.Protocol.loadResultSet(Protocol.java:61)\n\tat com.amazon.opendistroforelasticsearch.sql.executor.format.Protocol.<init>(Protocol.java:48)\n\tat com.amazon.opendistroforelasticsearch.sql.executor.format.PrettyFormatRestExecutor.execute(PrettyFormatRestExecutor.java:65)\n\tat com.amazon.opendistroforelasticsearch.sql.executor.format.PrettyFormatRestExecutor.execute(PrettyFormatRestExecutor.java:42)\n\tat com.amazon.opendistroforelasticsearch.sql.executor.AsyncRestExecutor.lambda$async$1(AsyncRestExecutor.java:104)\n\tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:660)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\n",
    "type": "java.lang.IllegalArgumentException"
  },
  "status": 500
}
```
It would be very useful to support index patterns

Regards!

**Comment by dai-chen** [comment] 2019-03-20 16:44
Thanks for reporting this issue. We're looking into it.

**Comment by dai-chen** [comment] 2019-03-20 18:26
We identified the root cause in our code. Will try to fix it soon.

**Comment by HernanMora** [comment] 2019-03-20 18:52
> We identified the root cause in our code. Will try to fix it soon.

Thank you! Let me know when it's fixed so I can follow up on this.

**Comment by dai-chen** [comment] 2019-03-20 18:55
> > We identified the root cause in our code. Will try to fix it soon.
> 
> Thank you! Let me know when it's fixed so I can follow up on this.

Sure. Will keep you posted here.

**Comment by dai-chen** [comment] 2019-03-25 19:22
Fixed and merged to master.

**Closed by dai-chen** 2019-03-25 19:22 UTC
Labels: bug
