### ISSUE TITLE
can not build on mac

### ISSUE THREAD

**Issue by luweijie007** [opendistro-for-elasticsearch/sql#338] opened 2020-01-09 07:01 UTC
![image](https://user-images.githubusercontent.com/7186190/72045238-97e30980-32f0-11ea-85ad-684ce2f0579b.png)

first error path has blank? second error If I need run some RMIServer?

**Comment by dai-chen** [comment] 2020-01-09 18:02
Hi @luweijie007 , I think that was caused by integTestCluster process hung there which was created by previous run and didn't exit normally.

You can check out its process ID (`ps aux | grep -i elasticsearch` or integTestRunner) and kill it. Please have a look at our Development Guide: https://github.com/opendistro-for-elasticsearch/sql/blob/master/docs/developing.rst#gradle-build

**Comment by dai-chen** [comment] 2020-01-29 21:09
Closing as no update from the requester.

**Closed by dai-chen** 2020-01-29 21:09 UTC
Labels: build
