### ISSUE TITLE
ODFE 1.12.0: Query does not execute while being similar to example in the documentation

### ISSUE THREAD

**Issue by ict-one-nl** [opendistro-for-elasticsearch/sql#1021] opened 2021-01-29 15:26 UTC
ODFE 1.12.0

Query: SELECT e.measurement_name FROM telegraf* AS e, e.http_input_jobstatus.Content AS p

Based on: https://opendistro.github.io/for-elasticsearch-docs/docs/sql/partiql/#example-1-unnesting-a-nested-collection

Result: 

```
Telegraf*: Bad Request, this query is not runnable. 
 
{
  "error": {
    "reason": "Invalid SQL query",
    "details": "Failed to parse query due to offending symbol [AS] at: 'SELECT e.measurement_name FROM telegraf* AS e, e.http_input_jobstatus.Content AS' <--- HERE... More details: Expecting tokens in {<EOF>, ';'}",
    "type": "SyntaxAnalysisException"
  },
  "status": 400
}
```

Data structure:

![image](https://user-images.githubusercontent.com/2643715/106293794-ae873600-624e-11eb-96e9-964ccaf90004.png)

Query: SELECT e.measurement_name FROM telegraf* AS e
Does work though, it's in the ", e.http_input_jobstatus.Content AS p" part where it goes wrong.

**Comment by dai-chen** [comment] 2021-01-29 16:53
@neographikal Thanks for reporting the issue! I can reproduce the syntax error by your query. But I found no issue in latest code. Will investigate.

**Comment by neographikal** [comment] 2021-01-29 17:41
Great, thanks!

**Comment by sandervandegeijn** [comment] 2021-02-22 15:35
Any news, can  I help to diagnose further? :)

**Comment by dai-chen** [comment] 2021-03-01 22:26
@ict-one-nl Sorry for the late response! I tested your query and the root cause is we don't support deep nested nested fields like your `e.http_input_jobstatus.Content`. Even if it can pass the parser, our current impl won't give correct response.

The query can be parsed if you change it to `SELECT e.measurement_name FROM telegraf* AS e, e.http_input_jobstatus AS p ...`. Let me know if anything else. Thanks!

**Comment by dai-chen** [comment] 2021-03-11 18:34
Closing. Feel free to reopen if anything else. Thanks!

**Closed by dai-chen** 2021-03-11 18:34 UTC
Labels: SQL

**Comment by sandervandegeijn** [comment] 2021-03-16 22:20
Sorry for my late reply, have had very busy weeks. I tried that as well but:

![image](https://user-images.githubusercontent.com/2643715/111387478-10d8b080-86ae-11eb-9a33-aaba463f6d81.png)

"This query is not explainable." and does not return results in ODFE 1.13.0

The query in my first post should work according to the documentation, shouldn't the documentation be changed? :)
