### ISSUE TITLE
Can not disable semantic check

### ISSUE THREAD

**Issue by shantanuo** [opendistro-for-elasticsearch/sql#976] opened 2021-01-08 05:03 UTC
The index name with dots or dash (for e.g. `cwl-2021.01.06`) works in PPL but not in SQL with back-ticks. Tried to change the settings as per this troubleshooting page.

https://github.com/opendistro-for-elasticsearch/sql/blob/develop/docs/user/dql/troubleshooting.rst

But getting an error because AWS is "fully managed" and does not allow setting modification. 

```
PUT /_cluster/settings
{
  "persistent" : {
    "opendistro.sql.query.analysis.enabled" : false
  }
}
```

`{"Message":"Your request: '/_cluster/settings' payload is not allowed."}`

Ref: https://github.com/opendistro-for-elasticsearch/sql/issues/322

**Comment by anirudha** [comment] 2021-01-08 05:14
Which Opendistro version can we use to reproduce this?

**Comment by shantanuo** [comment] 2021-01-08 05:26
I am using 7.9 version of AWS elasticsearch Service.

**Comment by dai-chen** [comment] 2021-01-08 18:37
@shantanuo Our troubleshooting doc and ODFE doc seems out of date. Here is the SQL setting endpoint: https://github.com/opendistro-for-elasticsearch/sql/blob/master/docs/user/admin/settings.rst#opendistro-sql-engine-new-enabled

Will confirm and send PR to update our doc. Thanks!

**Comment by dai-chen** [comment] 2021-01-08 19:12
@shantanuo I think we can keep our ODFE doc as it is since I found we've clarified this on AWS doc: https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/sql-support.html

"The Open Distro for Elasticsearch SQL plugin includes many tuneable settings, but on Amazon ES, use the _opendistro/_sql/settings path rather than the standard _cluster/settings path: ..."

**Comment by dai-chen** [comment] 2021-01-08 21:14
Closing. Feel free to reopen if any other question. Thanks!

**Closed by dai-chen** 2021-01-08 21:14 UTC
Labels: documentation

**Comment by shantanuo** [comment] 2021-01-09 05:08
I am still not able to use certain indices in SQL query. 

I used the AWS path as suggested:

```
PUT /_opendistro/_sql/settings
{
  "persistent" : {
    "opendistro.sql.query.analysis.enabled" : false
  }
}
```

Got this response:

```
{
  "acknowledged" : true,
  "persistent" : {
    "opendistro" : {
      "sql" : {
        "query" : {
          "analysis" : {
            "enabled" : "false"
          }
        }
      }
    }
  },
  "transient" : { }
}

```

**Comment by dai-chen** [comment] 2021-01-11 17:35
@shantanuo did you see different or same error? I just tested and didn't see issue after semantic check disabled.

```
POST cwl-2021.01.06/_doc
{
  "test": 123
}

POST _opendistro/_sql
{
  "query": """
    SELECT * FROM cwl-2021.01.06
  """
}
{
  "schema": [{
    "name": "test",
    "type": "long"
  }],
  "total": 1,
  "datarows": [[123]],
  "size": 1,
  "status": 200
}
```

**Comment by shantanuo** [comment] 2021-01-12 04:30
It is working correctly as expected now. May be on that day it was browser cache issue or something? :)

**Comment by dai-chen** [comment] 2021-01-12 04:40
> It is working correctly as expected now. May be on that day it was browser cache issue or something? :)

Cool. Happy to hear that! 👍
