### ISSUE TITLE
Problems with null values in Group By fields

### ISSUE THREAD

**Issue by HernanMora** [opendistro-for-elasticsearch/sql#364] opened 2020-02-04 13:29 UTC
Hi

It is not possible to make a query in which you want to know how many records without value exist.

I did the test with Elasticsearch 7.4.2 and OpenDistro SQL 1.4.0.0

Example:

```javascript

PUT test_null
{
  "mappings": {
    "properties": {
      "id": {
        "type": "keyword"
      },
      "code": {
        "type": "keyword"
      },
      "description": {
        "type": "keyword"
      }
    }
  }
}

PUT test_null/_doc/1
{
  "id": 1,
  "code": "0001",
  "description": "description 1"
}

PUT test_null/_doc/2
{
  "id": 2,
  "description": "description 2"
}

PUT test_null/_doc/3
{
  "id": 3,
  "code": "0003",
  "description": "description 3"
}

PUT test_null/_doc/4
{
  "id": 4,
  "description": "description 4"
}

PUT test_null/_doc/5
{
  "id": 5,
  "description": "description 5"
}

PUT test_null/_doc/5
{
  "id": 5,
  "code": "0003",
  "description": "description 5"
}

POST _opendistro/_sql?format=jdbc
{
  "query": "select * from test_null"
}

POST _opendistro/_sql?format=jdbc
{
  "query": "select code, count(code) from test_null group by code"
}

POST _opendistro/_sql?format=jdbc
{
  "query": "select code, count(code) from test_null where code is not null group by code"
}

POST _opendistro/_sql?format=jdbc
{
  "query": "select code, count(code) from test_null where code is null group by code"
}

```
Is there any way to be able to perform this type of queries?
Regards!

**Comment by abbashus** [comment] 2020-02-04 17:41
Thanks @HernanMora , will have a look if this is by design or some bug.

**Comment by dai-chen** [comment] 2020-02-04 18:15
@HernanMora The reason why null/missing value is not included in result is explained a little here: https://github.com/opendistro-for-elasticsearch/sql/pull/206.

I just tried different workarounds, ex. `GROUP BY CASE WHEN...`, `UNION ALL` 2 queries etc. This one worked for me. It's basically the same idea as `CASE WHEN` to convert NULL to another value so that Elasticsearch will take it into account when aggregation.

```
POST _opendistro/_sql?format=jdbc
{
  "query": """
    SELECT IFNULL(code, 'NULL'), COUNT(*) FROM test_null GROUP BY 1
  """
}

{
  "schema": [
    {
      "name": "ifnull(code)",
      "type": "double"
    },
    {
      "name": "COUNT(*)",
      "type": "integer"
    }
  ],
  "total": 3,
  "datarows": [
    [
      "0003",
      2
    ],
    [
      "NULL",
      2
    ],
    [
      "0001",
      1
    ]
  ],
  "size": 3,
  "status": 200
}
```

Note that there are 2 PUT requests for doc no.5.

**Comment by dai-chen** [comment] 2020-02-04 18:31
I found out that in other database (MySQL) NULL is returned. I think this is another semantic inconsistency between ours and SQL standard. Need to figure out how to fix this rather than ask user to work it around by themselves.

**Comment by dai-chen** [comment] 2020-02-04 19:20
To follow the SQL standard, Elasticsearch missing aggregation is needed: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-missing-aggregation.html.

It's straightforward to aggregate on single field by adding a missing aggregation:

```
POST test_null/_search
{
  "from" : 0,
  "size" : 0,
  "_source" : {
    "includes" : [
      "code"
    ],
    "excludes" : [ ]
  },
  "stored_fields" : "code",
  "aggregations" : {
    "code" : {
      "terms" : {
        "field" : "code",
        "size" : 200,
        "min_doc_count" : 1,
        "shard_min_doc_count" : 0,
        "show_term_doc_count_error" : false,
        "order" : [
          {
            "_count" : "desc"
          },
          {
            "_key" : "asc"
          }
        ]
      }
    },
    "null_code" : {
        "missing" : { "field" : "code" }
    }
  }
}

{
  "took" : 13,
  "timed_out" : false,
  "_shards" : {
    "total" : 9,
    "successful" : 9,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 5,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  },
  "aggregations" : {
    "null_code" : {
      "doc_count" : 2
    },
    "code" : {
      "doc_count_error_upper_bound" : 0,
      "sum_other_doc_count" : 0,
      "buckets" : [
        {
          "key" : "0003",
          "doc_count" : 2
        },
        {
          "key" : "0001",
          "doc_count" : 1
        }
      ]
    }
  }
}
```

But multi-field case should also be taken care of too. Here is the sample response in MySQL:

```
CREATE TABLE test(
  id INTEGER,
  name VARCHAR(100)
);

INSERT INTO test VALUES (1, 'hello');
INSERT INTO test VALUES (NULL, 'hello');
INSERT INTO test VALUES (2, NULL);
INSERT INTO test VALUES (NULL, NULL);

SELECT id, name, COUNT(*) FROM test GROUP BY id, name;

id     | name   | COUNT(*)
------ | ------ | ----------
(null) | (null) | 1
(null) | hello  | 1
1      | hello  | 1
2      | (null) | 1
```

**Comment by dai-chen** [comment] 2020-02-04 23:56
As @abbashus suggested, Composite Aggregation API can handle missing bucket: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-composite-aggregation.html. Need to test if it can handle multiple missing bucket. We should switch to this from Term Aggregation soon.

```
GET test_null/_search
{
    "aggs" : {
      "my_buckets": {
          "composite" : {
              "sources" : [
                  { "code": { "terms" : { "field": "code", "missing_bucket": true } } }
              ]
          }
      }
   }
}

{
  "took" : 7,
  "timed_out" : false,
  "_shards" : {
    "total" : 9,
    "successful" : 9,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 6,
      "relation" : "eq"
    },
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "test_null",
        "_type" : "_doc",
        "_id" : "5",
        "_score" : 1.0,
        "_source" : {
          "id" : 5,
          "code" : "0003",
          "description" : "description 5"
        }
      },
      {
        "_index" : "test_null",
        "_type" : "_doc",
        "_id" : "6",
        "_score" : 1.0,
        "_source" : {
          "id" : 6,
          "code" : null,
          "description" : "description 5"
        }
      },
      {
        "_index" : "test_null",
        "_type" : "_doc",
        "_id" : "4",
        "_score" : 1.0,
        "_source" : {
          "id" : 4,
          "description" : "description 4"
        }
      },
      {
        "_index" : "test_null",
        "_type" : "_doc",
        "_id" : "2",
        "_score" : 1.0,
        "_source" : {
          "id" : 2,
          "description" : "description 2"
        }
      },
      {
        "_index" : "test_null",
        "_type" : "_doc",
        "_id" : "3",
        "_score" : 1.0,
        "_source" : {
          "id" : 3,
          "code" : "0003",
          "description" : "description 3"
        }
      },
      {
        "_index" : "test_null",
        "_type" : "_doc",
        "_id" : "1",
        "_score" : 1.0,
        "_source" : {
          "id" : 1,
          "code" : "0001",
          "description" : "description 1"
        }
      }
    ]
  },
  "aggregations" : {
    "my_buckets" : {
      "after_key" : {
        "code" : "0003"
      },
      "buckets" : [
        {
          "key" : {
            "code" : null
          },
          "doc_count" : 3
        },
        {
          "key" : {
            "code" : "0001"
          },
          "doc_count" : 1
        },
        {
          "key" : {
            "code" : "0003"
          },
          "doc_count" : 2
        }
      ]
    }
  }
}
```

**Comment by penghuo** [comment] 2020-09-11 16:51
The issue has been fixed in new query engine (which is experimental and disabled by default). You can enable it to preview by changing the plugin setting: https://github.com/opendistro-for-elasticsearch/sql/blob/master/docs/user/admin/settings.rst#opendistro-sql-engine-new-enabled. Thanks!

**Closed by penghuo** 2020-09-11 16:51 UTC
Labels: enhancement
