### ISSUE TITLE
Dot character in index name results in an error in Query Workbench

### ISSUE THREAD

**Issue by nicolaslledo** [opendistro-for-elasticsearch/sql#862] opened 2020-11-27 10:58 UTC
```
SELECT 
message.*
FROM  siouxsso-beat-accesslog-2020.11
limit 10;
```

results in : no response in the response panel

**Comment by chloe-zh** [comment] 2020-11-27 20:11
Hi @nicolaslledo , thanks for reporting this issue! I reproduced this error, this was due to the index name with dot cannot pass our semantic analyzer in the old engine. Could you give it another try by turn off the semantic analyzer (see [Query analysis setting](https://github.com/penghuo/sql/blob/sort-aggregation-push-down/docs/user/admin/settings.rst#opendistro-sql-query-analysis-enabled)) and quote the index with back-ticks in the query, for example:

**1. Turn off semantic analyzer**

In bash
```
curl -H 'Content-Type: application/json' -X PUT localhost:9200/_opendistro/_sql/settings -d '{
  "transient" : {
    "opendistro.sql.query.analysis.enabled" : "false"
  }
}'
```
Or in DevTools
```
PUT _opendistro/_sql/settings
{
  "transient" : {
    "opendistro.sql.query.analysis.enabled" : "false"
  }
}
```

**2. Backticks quote the index**

Run the following query:
```
SELECT message.* FROM  `siouxsso-beat-accesslog-2020.11` limit 10;
```

---

Besides, here is another option to make it work by enabling our new engine (see [New engine setting](https://github.com/penghuo/sql/blob/sort-aggregation-push-down/docs/user/admin/settings.rst#opendistro-sql-engine-new-enabled)):
```
PUT _opendistro/_sql/settings
{
  "transient" : {
    "opendistro.sql.engine.new.enabled" : "false"
  }
}
```
And the query should also be working if you quote the index with backticks. One thing is the `LIMIT` keyword is not supported in the new engine yet but pending merge now (#851 ), but basic queries without LIMIT and OFFSET should be working, for example:
```
SELECT message.* FROM  `siouxsso-beat-accesslog-2020.11`
```

**Comment by nkavian** [comment] 2020-12-02 23:51
I was affected by this too. I ended up renaming my indexes before I saw this write up.

**Comment by nicolaslledo** [comment] 2020-12-04 08:47
I have enabled the new engine (your example says false, I used true) and the backtick quotes just works fine. 
Thank you.

**Comment by dai-chen** [comment] 2020-12-10 21:19
Closing now. Feel free to reopen if needed. Thanks!

**Closed by dai-chen** 2020-12-10 21:19 UTC
