### ISSUE TITLE
date range

### ISSUE THREAD

**Issue by donggong** [opendistro-for-elasticsearch/sql#481] opened 2020-05-22 15:01 UTC
I want to this:
     select count(create_date2) from xx  group by range(create_date2,'format'='yyyy-MM-dd','now-8d','now')
The create_date2 is date type.

failed

**Comment by dai-chen** [comment] 2020-05-26 23:25
Hi @donggong, sorry for the delay. Could you post your test data and exception you saw? So we can reproduce the issue quickly.

**Comment by donggong** [comment] 2020-06-28 08:05
I used es dsl.

**Comment by dai-chen** [comment] 2020-08-13 20:59
Closing due to insufficient info to investigate. Feel free to reopen as needed.

**Closed by dai-chen** 2020-08-13 20:59 UTC
Labels: investigation, question
