### ISSUE TITLE
SQL - Like operator behavior using curl or jdbc

### ISSUE THREAD

**Issue by Ncoati** [opendistro-for-elasticsearch/sql#1076] opened 2021-03-17 18:16 UTC
Executing a query using the like operator with a space, dash and possibly other characters leads to an empty resultset when using curl or a jdbc connection.

`Select * from islands where name like '%Isle %`

`>> curl -XPOST https://localhost:9200/_opendistro/_sql -u 'admin:admin' -k -H 'Content-Type: application/json' -d
{"query":"Select * from islands where name like ?", "parameters": [{"value":"%Isle %", "type":"keyword"}], "fetch_size":0 }
`

Executing the query using the Query Workbench is returning the correct results.

I am using the latest versions available.

**Comment by dai-chen** [comment] 2021-03-17 20:00
@Ncoati Thanks for reporting the issue! Could you share your index data for our testing? And you mean your LIKE query worked in Query Workbench but returned nothing using curl/JDBC driver?

**Comment by Ncoati** [comment] 2021-03-17 20:49
Here is some sample data:
`curl -XPUT https://localhost:9200/islands/_doc/1 -u 'admin:admin' -k -H 'Content-Type: application/json' -d '{"name":"Isle of Man"}'`
`curl -XPUT https://localhost:9200/islands/_doc/2 -u 'admin:admin' -k -H 'Content-Type: application/json' -d '{"name":"Galapagos Islands"}'`
`curl -XPUT https://localhost:9200/islands/_doc/3 -u 'admin:admin' -k -H 'Content-Type: application/json' -d '{"name":"Tasmania"}'`
`curl -XPUT https://localhost:9200/islands/_doc/4 -u 'admin:admin' -k -H 'Content-Type: application/json' -d '{"name":"Test-Island"}'`

Yes, you are correct. Executing the following query returns no data:
`curl -XPOST https://localhost:9200/_opendistro/_sql -u 'admin:admin' -k -H 'Content-Type: application/json' -d '{"query":"Select * from islands where name like ? ","parameters":[{"value":"%Isle %","type":"keyword"}],"fetch_size":0}'`

As soon as there is a space or dash in the parameter value, no data is being returned.

**Comment by dai-chen** [comment] 2021-03-17 21:28
Thanks for the info! I can reproduce the issue from my side:

```
PUT islands/_doc/1
{"name":"Isle of Man"}

POST _opendistro/_sql/_explain
{
  "query": "SELECT * FROM islands WHERE name LIKE ? ",
  "parameters":[{"value":"%Isle %","type":"keyword"}]
}
{
  "from" : 0,
  "size" : 200,
  "query" : {
    "bool" : {
      "filter" : [
        {
          "bool" : {
            "must" : [
              {
                "wildcard" : {
                  "name" : {
                    "wildcard" : "*Isle *",
                    "boost" : 1.0
                  }
                }
              }
            ],
            "adjust_pure_negative" : true,
            "boost" : 1.0
          }
        }
      ],
      "adjust_pure_negative" : true,
      "boost" : 1.0
    }
  }
}
```

**Comment by dai-chen** [comment] 2021-03-17 21:45
Root cause: Because our new SQL engine (just released in the latest version) doesn't support prepared statement, your query was handled by legacy engine by fallback mechanism. The legacy engine had issue rewriting text field to `text.field` (you can compare the "name" in explain outputs above). This caused empty response.

Workarounds:

1. Avoid prepared statement for now

```
POST _opendistro/_sql/_explain
{
  "query": "SELECT * FROM islands WHERE name LIKE '%Isle %' "
}
```

2. Add `.keyword` in your query explicitly

```
POST _opendistro/_sql
{
  "query": "SELECT * FROM islands WHERE name.keyword LIKE ? ",
  "parameters":[{"value":"%Isle %","type":"keyword"}]
}
```

**Comment by Ncoati** [comment] 2021-03-18 07:16
Since I am using jdbc for my queries, I can only use your suggested second workaround, which is working fine. Thank you!

**Comment by dai-chen** [comment] 2021-03-18 16:14
> Since I am using jdbc for my queries, I can only use your suggested second workaround, which is working fine. Thank you!

You're welcome! Closing now. Feel free to reopen if anything else. Thanks!

**Closed as completed by dai-chen** 2021-03-18 16:14 UTC
Labels: SQL

**Comment by dai-chen** [comment] 2021-03-29 20:11
> Since I am using jdbc for my queries, I can only use your suggested second workaround, which is working fine. Thank you!

The prepared statement support is already added in PR above. Thanks!
