### ISSUE TITLE
Parsing Exception when WHERE clause has true/false in CONDITION

### ISSUE THREAD

**Issue by Nitinrajyadav** [opendistro-for-elasticsearch/sql#127] opened 2019-07-23 12:35 UTC
> `	"query": "SELECT * FROM productsindex WHERE activeFlag = true" `
Throws 
 **"Failed to parse SqlExpression of type class com.alibaba.druid.sql.ast.expr.SQLBooleanExpr. expression value: xTRUE"**

my mappings are like
```
"mappings": {
            "properties": {
.......
                "activeFlag": {
                    "type": "boolean",
                    "fields": {
                        "raw": {
                            "type": "keyword"
                        }
                    }
                }
......
}}
```

**Comment by Nitinrajyadav** [comment] 2019-07-23 12:39
For a workaround, I can do 
> 	"query": "SELECT * FROM productsindex WHERE activeFlag = 'true'" 
as I have it as a raw field of type keyword

/_explain
```
{
    "from": 0,
    "size": 200,
    "query": {
        "bool": {
            "filter": [
                {
                    "bool": {
                        "must": [
                            {
                                "term": {
                                    "activeFlag.raw": {
                                        "value": "true",
                                        "boost": 1
                                    }
                                }
                            }
                        ],
                        "adjust_pure_negative": true,
                        "boost": 1
                    }
                }
            ],
            "adjust_pure_negative": true,
            "boost": 1
        }
    }
}
```

**Comment by dai-chen** [comment] 2019-07-23 16:52
Thanks for reporting! I recall I came across this before. Let me reproduce the issue to investigate.

**Comment by dai-chen** [comment] 2019-07-23 20:52
I just did some quick check. It seems this simple fix works: https://github.com/opendistro-for-elasticsearch/sql/compare/master...dai-chen:boolean-query-support.

I tested =, IS, IS NOT with true/false. Need more verification and unit/integration test. Leave this for people who wants to contribute. Will fix it later if I have more time and no response from community.

```
POST _opendistro/_sql
{
  "query": "SELECT * FROM my_index WHERE is_published = true"
}

PUT my_index
{
  "mappings": {
    "properties": {
      "is_published": {
        "type": "boolean"
      }
    }
  }
}

POST my_index/_doc/1
{
  "is_published": "true" 
}

POST my_index/_doc/2
{
  "is_published": "false" 
}
```

**Comment by Nitinrajyadav** [comment] 2019-07-24 20:44
@dai-chen I'd love to contribute, but the thing is, I've worked with Java only in Android ecosystem(Android also uses the gradle build system so I'm familiar with that), but I'd have a hard time with testing my changes, as I don't really have any clue about the required setup.

> If you guys can put more details about the required setup, that would be really helpful, for guys like me.
> A little more documentation about the current features/limitations/roadmap would be a great idea in that regard as well.

**Comment by dai-chen** [comment] 2019-07-24 23:08
@Nitinrajyadav Good to hear that. If you're interested, you could follow the instruction in README to build our plugin with your fix and install to your local Elasticsearch. Then you may want to configure your IDE for remote debugger and add unit/integration test (refer to existing code in test folder). Not necessary to fix this by yourself this time but I think it's a good opportunity to learn :)

We're not doing good job at documentation. We will improve it in the near future.

**Comment by dai-chen** [comment] 2019-08-23 22:02
@Nitinrajyadav the issue is fixed now.

**Closed by dai-chen** 2019-08-23 22:02 UTC
Labels: good first issue
